  # Server settings
  server:
      port: 9090
#      contextPath: /weibo
      address: 192.168.1.106
      session-timeout: 30
#      tomcat.max-threads: 0
#      tomcat.uri-encoding: UTF-8

  # SPRING PROFILES
  spring:
    datasource:
        url: jdbc:mysql://localhost:3306/devdb?zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 200
        initialSize: 2
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    mvc:
        view.prefix: /WEB-INF/jsp/
        view.suffix: .jsp
    profiles:
        active: dev
  mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.paipaipai.entity
  debug: false

  jedis :
    pool :
      host : 127.0.0.1
      port : 6379
      config :
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis : 100000